### ISSUE TITLE
down and up

### ISSUE THREAD

**Issue by s1im3r00** [lu4p/ToRat#204]
I can't figure out where files are saved from the client, and how to select files to upload to the client using docker

**Comment by JustinTimperio** [comment]
These files are found in the docker container with the absolute path `ToRat/cmd/server/bots`

**Comment by s1im3r00** [comment]
thank you. but how do I select the right file to upload to the client? and how do i download a file from docker server to localhost.

**Comment by JustinTimperio** [comment]
The upload path is determined by your current path in the docker container. Downloading files from the docker container is not natively supported currently but that will be an upcoming feature depending on @lu4p and my availability to add these features. Currently, @lu4p is quite busy and merging in changes from my dev fork takes him time to review. 

That being said I expect to have at least a partial solution to this issue within the month. (lots to do first)

**Comment by JustinTimperio** [comment]
@s1im3r00 @lu4p This actually was really add since we already had a docker bind on `/dist_ext` within the container. By modifying some paths and settings, both the bots folder and the ToRat.db are now stored in `/dist_ext`. This means that the host will have direct access to all the most important files.

This feature currently only works in my dev branch but once I work with @lu4p we will get this merged into master

**Comment by JustinTimperio** [comment]
@s1im3r00 This feature has been merged. You can now easily upload and download files to the container
